"""upgrade_ai_schema

Revision ID: 3735025109f4
Revises: 
Create Date: 2026-05-13 14:08:26.442224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3735025109f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_scores', sa.Column('buying_stage', sa.String(), nullable=True))
    op.add_column('lead_scores', sa.Column('confidence', sa.Integer(), nullable=True))
    op.add_column('lead_scores', sa.Column('next_best_action', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('growth_stage', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('market_position', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('enrichment_confidence', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('buying_signals', sa.JSON(), nullable=True))
    op.add_column('leads', sa.Column('pain_points', sa.JSON(), nullable=True))
    op.add_column('leads', sa.Column('tech_stack', sa.JSON(), nullable=True))
    op.drop_constraint('leads_email_key', 'leads', type_='unique')
    op.create_index(op.f('ix_leads_company'), 'leads', ['company'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=True)
    op.create_index(op.f('ix_leads_industry'), 'leads', ['industry'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_industry'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_company'), table_name='leads')
    op.create_unique_constraint('leads_email_key', 'leads', ['email'])
    op.drop_column('leads', 'tech_stack')
    op.drop_column('leads', 'pain_points')
    op.drop_column('leads', 'buying_signals')
    op.drop_column('leads', 'enrichment_confidence')
    op.drop_column('leads', 'market_position')
    op.drop_column('leads', 'growth_stage')
    op.drop_column('leads', 'ai_summary')
    op.drop_column('lead_scores', 'next_best_action')
    op.drop_column('lead_scores', 'confidence')
    op.drop_column('lead_scores', 'buying_stage')
    # ### end Alembic commands ###
